version: "3.9"
services:
  app:
    build: .
    image: starwars-people:local
    ports:
      - "8080:8080"
    environment:
      SECURITY_JWT_SECRET: E7sJr3VjKkG4p2mQ9wA1tZc6R8uM5nX0B4fH7kP2sD9yL3eT6qW8rY1uI3oP6aZ
      STARWARS_BASE_URL: https://www.swapi.tech
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]